export const AppActions = {
    SET_CURRENT_LEVEL : 'SET_CURRENT_LEVEL',
    SET_CURRENT_POINTS : 'SET_CURRENT_POINTS',
    SET_SOUND_ON : 'SET_SOUND_ON',
    SET_SOUND_OFF : 'SET_SOUND_OFF',
    SET_HINT_LEVELS : 'SET_HINT_LEVELS',
    INIT_CURRENT_LEVEL : 'INIT_CURRENT_LEVEL',
    INIT_CURRENT_POINTS : 'INIT_CURRENT_POINTS'
};